### ISSUE TITLE
Contextual

### ISSUE THREAD

**Issue by raphaelsty** [dfdazac/blp#1]
Hi,

I really enjoyed your work and your model allows to handle knowledge graphs with text efficiently. I considered your model for different use cases and thus implemented it with unit tests and made it modular to easily integrate it into ml pipelines. It's available [here](https://github.com/raphaelsty/ckb). Thank you.

Have a good day.

**Comment by dfdazac** [comment]
Hi Raphael, thanks for pointing this out! Kudos on your clean implementation. I have added a reference to the README.

**Comment by raphaelsty** [comment]
Thank you ☺️
