### ISSUE TITLE
The FB15K-237 dataset error?

### ISSUE THREAD

**Issue by zhiweihu1103** [dfdazac/blp#2]
Hello, I may need your help. The number of entities in entity2text.txt (contains 14951 entities) and entity2textlong.txt (contains 14904 entities)  below the FB15K-237 dataset are different. Is the dataset error? Thx.

**Comment by dfdazac** [comment]
Hi, indeed we don't have long names for all entities. In those cases we resort to short descriptions, that can be found in the entity2text.txt file. If you look at `data.py` you will find that first we load data from entity2textlong.txt, and then from entity2text.text:

https://github.com/dfdazac/blp/blob/0567c3f7217d54afddd4d8bc06f4b80c4dbad273/data.py#L219-L220

**Comment by zhiweihu1103** [comment]
> Hi, indeed we don't have long names for all entities. In those cases we resort to short descriptions, that can be found in the entity2text.txt file. If you look at `data.py` you will find that first we load data from entity2textlong.txt, and then from entity2text.text:
> 
> https://github.com/dfdazac/blp/blob/0567c3f7217d54afddd4d8bc06f4b80c4dbad273/data.py#L219-L220

Thank you for you reply.
