### ISSUE TITLE
Is the pre-trained model for Wikidata5M available?

### ISSUE THREAD

**Issue by xhh232018** [dfdazac/blp#4]
Hello Daniel, I am very impressed by your work. Now I am trying to reproduce the experiment on link prediction task for Wikidata5M. I found that it needs nearly 5 days to finish the whole training process under my RTX A5000 GPU, which is quite time-consuming . Therefore, I am wondering if your pre-trained model is open-sourced.

**Comment by dfdazac** [comment]
Hi, thank you for your interest!
I'm currently organizing all the files to upload pretrained models to the repository for all datasets. I'm hoping this will be ready in the next week.

**Comment by dfdazac** [comment]
@xhh232018 I have uploaded pretrained models for most of the models and datasets. Please see [this updated section of the readme](https://github.com/dfdazac/blp/blob/01f1f040bce4b35db4fd51bd9bceedb5c13f0f72/README.md#pre-trained-models).
