### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by QingzhiHu** [dfdazac/blp#6]
In "Using your own data" section:

"
To generate inductive splits, you can use data/utils.py. If you run

python utils.py drop_entities --file=my-kg/all-triples.tsv
"
Since there is also a utils.py inside of the root folder which may cause confusion with the utils.py inside of the data folder (although it is specifically mentioned to use data/utils.py, however the command below needs to be executed inside of data folder while other commands all operate on the root folder level). Solutions:

Solution 1 (best):
python ./data/utils.py drop_entities --file=/data/my-kg/all-triples.tsv

Solution 2:
cd data
python utils.py drop_entities --file=my-kg/all-triples.tsv

**Comment by dfdazac** [comment]
Thanks @QingzhiHu , I agree this is confusing. I fixed it with your solution 1.
